# Schema for the configuration file of bulk content operation module.

bulk_content_operation.settings:
  type: config_object
  label: 'Bulk Content Operation Content Type Settings'
  mapping:
    allowed_types:
      type: sequence
      label: 'Content types bulk content operation can display on'
      sequence:
        type: string
        label: 'Content type'
     