enabled: 1
outage_action: '1'
overridden_schemes: {  }
scan_mode: '2'
verbosity: 1
mode_executable:
  executable_path: /usr/bin/clamscan
  executable_parameters: ''
mode_daemon_tcpip:
  hostname: localhost
  port: '3310'
mode_daemon_unixsocket:
  unixsocket: /var/run/clamav/clamd.ctl
_core:
  default_config_hash: 8lFEG9XVghDf6aSd4WXsDEbAlBuvpTBI3gxmUUt_jyY
