module:
  address: 0
  addtoany: 0
  admin_toolbar: 0
  advagg: 0
  advagg_bundler: 0
  advagg_css_minify: 0
  advagg_js_minify: 0
  advagg_mod: 0
  advagg_validator: 0
  aggregator: 0
  auto_entitylabel: 0
  autologout: 0
  ban: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  checklistapi: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  clamav: 0
  color: 0
  comment: 0
  conditional_fields: 0
  config: 0
  consumers: 0
  contact: 0
  contact_storage: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  easy_install: 0
  easychart: 0
  editor: 0
  editor_advanced_link: 0
  embed: 0
  entity: 0
  entity_block: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  geofield: 0
  geolocation: 0
  geolocation_google_places_api: 0
  google_analytics: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  jsonapi: 0
  layout_discovery: 0
  libraries: 0
  lightning_api: 0
  lightning_contact_form: 0
  lightning_core: 0
  lightning_landing_page: 0
  lightning_layout: 0
  lightning_media: 0
  lightning_media_document: 0
  lightning_media_image: 0
  lightning_page: 0
  lightning_roles: 0
  lightning_workflow: 0
  like_and_dislike: 0
  link: 0
  login_security: 0
  media_entity: 0
  media_entity_document: 0
  media_entity_image: 0
  memcache: 0
  menu_ui: 0
  message: 0
  message_example: 0
  message_notify: 0
  metatag: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_google_plus: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  node: 0
  openapi: 0
  openapi_redoc: 0
  options: 0
  page_cache: 0
  panelizer: 0
  panelizer_quickedit: 0
  panels: 0
  panels_ipe: 0
  paragraphs: 0
  path: 0
  phpexcel: 0
  poll: 0
  quickedit: 0
  rdf: 0
  realname: 0
  redirect: 0
  redirect_404: 0
  rest: 0
  scheduled_updates: 0
  schemata: 0
  schemata_json_schema: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  simple_oauth_extras: 0
  sitemap: 0
  smtp: 0
  social_api: 0
  styled_google_map: 0
  superfish: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  ultimate_cron: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_bootstrap: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_infinite_scroll: 0
  views_ui: 0
  votingapi: 0
  votingapi_widgets: 0
  webform: 0
  webform_ui: 0
  workbench: 0
  workbench_moderation: 0
  workbench_moderation_actions: 0
  xmlsitemap: 0
  xmlsitemap_custom: 0
  xmlsitemap_engines: 0
  contribute: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  lightning: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  openelections: 0
profile: lightning
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
